### ISSUE TITLE
Update the getting started guide

### ISSUE THREAD

**Issue by pupeno** [flexpointtech/repeater_world#174]
https://github.com/flexpointtech/repeater_world/wiki

**Comment by outrunthewolf** [comment]
I tried to PR to the wiki but couldn't figure out how? :D 

I figured if you list dependencies and links to their documentation, it would include better documentation than trying to keep this one up to date:



--- 

# Getting started

This should be a complete set of instructions to get RepeaterWorld up and running on your own computer. If something didn't work or it was missing and you figured it out, please update the docs.

## Dependencies:

- Docker: https://docs.docker.com/engine/install/
- Postgres: https://www.postgresql.org/download/
- Ruby >=3.1.2 : https://www.ruby-lang.org/en/documentation/installation/

## Running for the first time

First check out the code:

```bash
git clone git@github.com:flexpointtech/repeater_world.git
cd repeater_world
```

You first need to install dependencies:

```bash
bundle install
```

Now run the database (and any other services we may have added):

```bash
docker-compose up
```

That should leave PostgreSQL running on port 10401. The credentials can be found in [`docker-compose.yml`](https://github.com/flexpointtech/repeater_world/blob/main/docker-compose.yml)

Create the databases:

```bash
rake db:create
```

Run the migrations:

```bash
rake db:migrate
```

Generate sample data:

```bash
rake db:seed
```

Run the tests (or specs if you want to be fancy):

```bash
rake spec
```

If all of that worked you are in good shape.

Now run the server in development mode:

```bash
./bin/dev
```

Once that's done starting up, you can go to http://localhost:10400 and you'll see your local version of RepeaterWorld running.

- `bin/dev` is a script that runs two commands using [foreman](https://github.com/ddollar/foreman) and reading [Procfile.dev](https://github.com/flexpointtech/repeater_world/blob/main/Procfile.dev).
- One is `rails server` which runs Rails itself and the other one is `rake tailwindcss:watch` which compiles the [TailwindCSS](https://tailwindcss.com/) CSS as you change them. 

The latter is technically not needed if you are not changing CSS, but we all forget to start it and spent half an hour wondering why the margin is not getting wider.

# Environment Variables

## To configure the app.

* `DATABASE_URL`: the full database url with credentials to connect to, only used in production.
* `ALLOW_SAMPLE_DATA_GENERATION`: if it's `"true"`, generating sample data is allowed, something that blanks the database first. This should never be turned on in prod.
* `DELIVER_EMAILS`: if it's `"true"` emails will be delivered normally, if not, the headers will be re-written to be delivered to `SAFE_EMAIL_DEST`.
* `SAFE_EMAIL_DEST`: email address used in staging, review apps, dev, etc. that should receive emails when we are avoiding sending them to real users.
* `GOOGLE_ANALYTICS_ID`: the ID of the Google Analytics stream. When absent, Google Analytics is not loaded (good for dev, testing, staging).
* `FATHOM_ID`: the id to report analytics to Fathom. It's presence enables fathom.
* `HELPSCOUT_BEACON_ID`: the id of the HelpScout beacon (the chat bubble). It's presence enables the beacon.
* `SENTRY_DSN`: the DSN (aka key) for talking to Sentry for the backend end.
* `SENTRY_DSN_FE`: the DSN (aka key) for talking to Sentry for the front end.

## Defined by third parties and used

These are [defined by render.com](https://render.com/docs/environment-variables):

* `IS_PULL_REQUEST`: "true" if it's a pull request, that is, a review app.
* `RENDER`: "true" if the application is running in render.com.
* `RENDER_SERVICE_NAME`: the name of the service in render.com, this could be web, or queue or background job or something like that.

These are [defined by github actions](https://docs.github.com/en/actions/learn-github-actions/environment-variables):
* `CI`: always "true" while running in Github actions.

These are [defined by Heroku](https://devcenter.heroku.com/articles/dyno-metadata):
* `HEROKU_RELEASE_VERSION`: version number set by Heroku, it's used by Sentry (at least).
* `HEROKU_APP_NAME`: application name set by Heroku, it's used by Sentry (at least).

**Comment by pupeno** [comment]
I did a general update of this document and now you should have access to update it directly. I think.
