### ISSUE TITLE
Map search result - clusters of 2 or more markers only show 1 when clicked

### ISSUE THREAD

**Issue by IainJohnson** [flexpointtech/repeater_world#283]
Hi Pablo, many thanks, this is a real improvement over other resources!

If I do a map search, if I click a cluster with 2 or more repeaters at the identical same location, the map zooms in and only shows one marker. Examples are GB3TD and GB7TC on the same site near Swindon, or GB7BK and GB3RD on the same site near Reading. Tested in Edge and Firefox.

Many thanks! 73 Iain

**Comment by pupeno** [comment]
@IainJohnson this is now fixed, here's a short video about the issue: https://www.youtube.com/watch?v=BE9qdagfXrQ
