### ISSUE TITLE
Allow searching by grid square

### ISSUE THREAD

**Issue by pupeno** [flexpointtech/repeater_world#40]
Open questions:
- How do we convert from grid square to coordinates and vice-versa?
- Should we add a mini app to do the conversion for others?

**Comment by ntilley905** [comment]
I don't have any Ruby experience but the conversion from maidenhead to lat/long and vice versa just takes some math that a couple helper functions could take care of. There is a Python package that implements this trivially, I wonder if Ruby has the same?

I may be able to muddle together a helper function at least here but I would be helpless implementing it within the codebase elsewhere.

**Comment by pupeno** [comment]
@ntilley905 there seems to be a package that implements it here https://github.com/gmcintire/hamradio although it's a bit odd that it also implements call sign lookup with an arbitrary service. There's another one here: https://github.com/schrockwell/dx-grid. I might go with the latter.

I'm actually right now working on the geosearch form right now, making it possible to select different ways to specify the point of searching.

BTW, if you want a tour of the codebase, I'm happy to do one over videoconf, no strings attached.

**Comment by ntilley905** [comment]
That package does seem to be exactly what's needed! 

I may take you up on that offer at some point but let me get my feet wet with some Ruby basics first. It seems worth learning!

**Comment by pupeno** [comment]
@ntilley905 this is now implemented: https://youtu.be/aoNSGxFOpRE

**Comment by pupeno** [comment]
It ended up being more complex than I expected because I had to do quite a bit of cleanup.
